# Generated by Django 5.2.8 on 2025-11-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_item',
        ),
    ]
