# Generated by Django 5.2.8 on 2025-11-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0002_remove_order_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(related_name='orders', through='foodDelivery.OrderFoodItem', to='foodDelivery.fooditem'),
        ),
    ]
